name: redd-dev

services:
  redd-admin-backend:
    extends:
      file: docker-compose.yml
      service: redd-admin-backend
    environment:
      APP_ENV: development
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:5173,http://localhost:5174,http://localhost:5175}

  redd-postgres:
    extends:
      file: docker-compose.yml
      service: redd-postgres

volumes:
  postgres-data:
