ROOT_DIR := ..

.PHONY: help dev-up dev-db-up dev-down dev-logs dev-migrate docker-up docker-down docker-logs docker-migrate

help:
	$(MAKE) -C $(ROOT_DIR) help

dev-up:
	$(MAKE) -C $(ROOT_DIR) dev-up

dev-db-up:
	$(MAKE) -C $(ROOT_DIR) dev-db-up

dev-down:
	$(MAKE) -C $(ROOT_DIR) dev-down

dev-logs:
	$(MAKE) -C $(ROOT_DIR) dev-logs

dev-migrate:
	$(MAKE) -C $(ROOT_DIR) dev-migrate

docker-up:
	$(MAKE) -C $(ROOT_DIR) docker-up

docker-down:
	$(MAKE) -C $(ROOT_DIR) docker-down

docker-logs:
	$(MAKE) -C $(ROOT_DIR) docker-logs

docker-migrate:
	$(MAKE) -C $(ROOT_DIR) docker-migrate
